# Generated by Django 4.2 on 2023-04-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Form", new_name="Forms",),
    ]
