# Generated by Django 4.2 on 2023-04-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_rename_form_forms"),
    ]

    operations = [
        migrations.DeleteModel(name="Forms",),
    ]
