# Generated by Django 4.2 on 2023-04-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_forms_delete_formulaire"),
    ]

    operations = [
        migrations.DeleteModel(name="Forms",),
    ]
