# Generated by Django 4.2 on 2023-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaire",
            name="montant",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
