# Generated by Django 4.2 on 2023-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_formulaire_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(default=None, upload_to="photos"),
        ),
    ]
