# Generated by Django 4.2 on 2023-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_formulaire_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.DecimalField(decimal_places=3, default=45, max_digits=3),
        ),
    ]
