# Generated by Django 4.2 on 2023-04-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_alter_formulaire_montant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire", name="montant", field=models.IntegerField(),
        ),
    ]
