# Generated by Django 4.2 on 2023-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0012_alter_formulaire_montant_alter_formulaire_nom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(blank=True, default=None, upload_to="photos"),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(blank=True, default=" ", max_length=20),
        ),
    ]
