# Generated by Django 4.2 on 2023-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_alter_formulaire_image_alter_formulaire_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(blank=True),
        ),
    ]
