# Generated by Django 4.2 on 2023-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0017_remove_formulaire_montant_remove_formulaire_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(default="", max_length=25),
        ),
    ]
