# Generated by Django 4.2 on 2023-04-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_alter_formulaire_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(default=None, upload_to="photos"),
        ),
    ]
