# Generated by Django 4.2 on 2023-04-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0021_alter_formulaire_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(blank=True, default=None, upload_to="photos"),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(blank=True, default="", max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(blank=True, default="", max_length=25, null=True),
        ),
    ]
