# Generated by Django 4.2 on 2023-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0024_alter_formulaire_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
