# Generated by Django 4.2 on 2023-04-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0025_alter_formulaire_montant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(default="", max_length=25, null=True),
        ),
    ]
