# Generated by Django 4.2 on 2023-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0026_alter_formulaire_nom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(default="", max_length=25, null=True),
        ),
    ]
