# Generated by Django 4.2 on 2023-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0028_alter_formulaire_image_alter_formulaire_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
