# Generated by Django 4.2 on 2023-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0032_alter_formulaire_image_alter_formulaire_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(default=None, upload_to="photos"),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="montant",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="nom",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(default="", max_length=25),
        ),
    ]
