# Generated by Django 4.2 on 2023-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0035_alter_formulaire_image_alter_formulaire_nom_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="formulaire", name="image",),
    ]
