# Generated by Django 4.2 on 2023-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0036_remove_formulaire_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulaire",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="photos"),
        ),
    ]
