# Generated by Django 4.2 on 2023-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0037_formulaire_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="formulaire", name="nom",),
        migrations.AddField(
            model_name="formulaire",
            name="email",
            field=models.EmailField(default="", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="formulaire",
            name="prenom",
            field=models.CharField(default="", max_length=40, null=True),
        ),
    ]
